Vagrant.configure("2") do |config|

    config.vm.define "lab-dc01", primary: true do |lab-dc01|
        lab-dc01.vm.box = "gusztavvargadr/windows-server-2022-standard-core" #"gusztavvargadr/windows-server"
        lab-dc01.vm.network "public_network", bridge: "External Switch"
        lab-dc01.vm.provider "hyperv"
        lab-dc01.vm.hostname = "lab-dc01"
        lab-dc01.vm.synced_folder '.', '/vagrant', disabled: true

        srv01.vm.provider "hyperv" do |h|
            h.enable_virtualization_extensions = false
            h.linked_clone = false
            h.cpus = 2
            h.memory = 4096
            h.vmname = "lab-dc01"
            h.auto_stop_action = "ShutDown" # (ShutDown, TurnOff, Save)
            h.auto_start_action = "Nothing" # (Nothing, StartIfRunning, Start)
            # h.vlan_id = "100"
        end

        srv01.vm.provision "ansible" do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "playbook.yml"
        end
    end
end